pluginManagement {
    def kotlinVersion = providers.gradleProperty("kotlinVersion").getOrElse("2.2.10")

    repositories {
        mavenCentral()
        gradlePluginPortal()
        google()
    }
    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case "com.android.library":
                    useVersion("9.3.1")
                    break
                case "org.jetbrains.kotlin.android":
                    useVersion(kotlinVersion)
                    break
                case "org.jetbrains.kotlin.jvm":
                    useVersion(kotlinVersion)
                    break
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()

    }
}

def tauriApiDir = file('./.tauri/tauri-api')
if (tauriApiDir.exists()) {
    include ':tauri-android'
    project(':tauri-android').projectDir = tauriApiDir
}
