[default]
description = "Default permissions for fs-resolver plugin (all resolve commands)"
permissions = [
    "allow-get-fs-environment",
    "allow-resolve-mac-path",
    "allow-resolve-ios-path",
    "allow-resolve-linux-path",
    "allow-resolve-win32-path",
    "allow-resolve-windows-application-data-path",
    "allow-resolve-android-path",
    "allow-resolve-android-path-collection",
]
